# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_dialog(object):
    def setupUi(self, main_dialog):
        main_dialog.setObjectName("main_dialog")
        main_dialog.resize(431, 407)
        self.pull_btn = QtWidgets.QPushButton(main_dialog)
        self.pull_btn.setGeometry(QtCore.QRect(180, 110, 75, 23))
        self.pull_btn.setObjectName("pull_btn")
        self.del_btn = QtWidgets.QPushButton(main_dialog)
        self.del_btn.setGeometry(QtCore.QRect(180, 220, 75, 23))
        self.del_btn.setObjectName("del_btn")
        self.push_btn = QtWidgets.QPushButton(main_dialog)
        self.push_btn.setGeometry(QtCore.QRect(180, 80, 75, 23))
        self.push_btn.setObjectName("push_btn")
        self.add_btn = QtWidgets.QPushButton(main_dialog)
        self.add_btn.setGeometry(QtCore.QRect(180, 190, 75, 23))
        self.add_btn.setObjectName("add_btn")
        self.login_btn = QtWidgets.QPushButton(main_dialog)
        self.login_btn.setGeometry(QtCore.QRect(180, 30, 75, 23))
        self.login_btn.setObjectName("login_btn")
        self.all_btn = QtWidgets.QListWidget(main_dialog)
        self.all_btn.setGeometry(QtCore.QRect(10, 30, 141, 351))
        self.all_btn.setObjectName("all_btn")
        self.selec_it = QtWidgets.QListWidget(main_dialog)
        self.selec_it.setGeometry(QtCore.QRect(280, 30, 141, 351))
        self.selec_it.setObjectName("selec_it")
        self.save_btn = QtWidgets.QPushButton(main_dialog)
        self.save_btn.setGeometry(QtCore.QRect(180, 330, 75, 23))
        self.save_btn.setObjectName("save_btn")
        self.Refresh_btn = QtWidgets.QPushButton(main_dialog)
        self.Refresh_btn.setGeometry(QtCore.QRect(180, 360, 75, 23))
        self.Refresh_btn.setObjectName("Refresh_btn")
        self.convert_btn = QtWidgets.QPushButton(main_dialog)
        self.convert_btn.setGeometry(QtCore.QRect(180, 300, 75, 23))
        self.convert_btn.setObjectName("convert_btn")

        self.retranslateUi(main_dialog)
        QtCore.QMetaObject.connectSlotsByName(main_dialog)

    def retranslateUi(self, main_dialog):
        _translate = QtCore.QCoreApplication.translate
        main_dialog.setWindowTitle(_translate("main_dialog", "Dialog"))
        self.pull_btn.setText(_translate("main_dialog", "<<<"))
        self.del_btn.setText(_translate("main_dialog", "del"))
        self.push_btn.setText(_translate("main_dialog", ">>>"))
        self.add_btn.setText(_translate("main_dialog", "add"))
        self.login_btn.setText(_translate("main_dialog", "login"))
        self.save_btn.setText(_translate("main_dialog", "save"))
        self.Refresh_btn.setText(_translate("main_dialog", "refresh"))
        self.convert_btn.setText(_translate("main_dialog", "convert"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_dialog = QtWidgets.QDialog()
    ui = Ui_main_dialog()
    ui.setupUi(main_dialog)
    main_dialog.show()
    sys.exit(app.exec_())
